### ISSUE TITLE
Question: How did you follow the tuts?

### ISSUE THREAD

**Issue by 50-Course** [PixelRifts/c-codebase#1]
Hi,

I came across your channel on YT, with your demo. I am a member of HMN. Although I do little systems work for now, mainly BE.

CAn you recommend how to follow through on the https://www.youtube.com/@Mr4thProgramming/playlists? Do I start with the base?

Thanks.

**Comment by PixelRifts** [comment]
I just implemented Base and OS from Allen's series. The rest of the things I implemented myself. I can't exactly tell you "how" to follow the series though, because I have no idea what your goal is. What I did was copied over stuff that I thought was important and good to have. A few things I thought maybe could work better If I did them differently (like the project structure)

**Comment by PixelRifts** [comment]
But yes, Base is the first playlist

**Comment by 50-Course** [comment]
Got it. Thank you.
